## Task 1

In [1]:
# 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

def compute_division():
    try:
        a = int(input('Enter the value of a = '))
        b = int(input('Enter the value of b = '))
        compute = a/b
        print("The division of {} and {} is {} ".format(a,b,compute))
    except Exception as e:
        print("{}  exception occured".format(e))
        print("Please enter non-zero value of b")
        print('\n')
        compute_division()

compute_division()

Enter the value of a = 10
Enter the value of b = 0
division by zero  exception occured
Please enter non-zero value of b


Enter the value of a = 10
Enter the value of b = 5
The division of 10 and 5 is 2.0 


In [2]:
# 2. Implement a Python program to generate all sentences where subject is in
# ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in
# ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]
# Output should come as below:
# Americans play Baseball.
# Americans play Cricket.
# Americans watch Baseball.
# Americans watch Cricket.
# Indians play Baseball.
# Indians play Cricket.
# Indians watch Baseball.
# Indians watch Cricket.



subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print(s+' '+ v +' '+ o)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

In [3]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

import numpy as np


def myVander(input_vector, n, increasing=False):
    
    if increasing:
        return [[i**(j) for j in range(n)] for i in input_vector]
    return [[i**(n-j-1) for j in range(n)] for i in input_vector]

def display_vander(m):
    for i in m:
        print(i)
    
input_vector = [1,2,3,4,5]
n=4

print("Using Built in Function Increasing True \n")
print(np.vander(input_vector, N=n, increasing=True))

print("\nUsing Manual Function Increasing True \n")
m = myVander(input_vector, n, True)
display_vander(m)

print('*'*100)
print("\nUsing Built in Function Increasing False \n")
print(np.vander(input_vector, N=n, increasing=False))

print("\nUsing Manual Function Increasing False \n")
m = myVander(input_vector, n, False)
display_vander(m)

Using Built in Function Increasing True 

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]

Using Manual Function Increasing True 

[1, 1, 1, 1]
[1, 2, 4, 8]
[1, 3, 9, 27]
[1, 4, 16, 64]
[1, 5, 25, 125]
****************************************************************************************************

Using Built in Function Increasing False 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

Using Manual Function Increasing False 

[1, 1, 1, 1]
[8, 4, 2, 1]
[27, 9, 3, 1]
[64, 16, 4, 1]
[125, 25, 5, 1]
